# Generated by Django 4.1.2 on 2023-03-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='text_edit.text')),
            ],
        ),
    ]
