# Generated by Django 4.1.2 on 2023-03-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_edit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='Parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='text_edit.text'),
        ),
    ]
